### ISSUE TITLE
Not showing up in kibana

### ISSUE THREAD

**Issue by oliverdroege** [flexmonster/pivot-kibana#12]
I installed it according to your guide.
After getting permission error for the package.json when trying to install the plugin with kibana as the use I used root and gave the kibana user rights afterwards.
I changed elasticsearch.yml and kibana.yml and restarted both.

When now going to my kibana UI the flexmonster pivot is missing in the menu.

Also see missing/wrong dependencies which popup when doing "yarn upgrade"
![yarn upgrade flexmonster](https://user-images.githubusercontent.com/54579924/65325671-cb6a1e80-dbaf-11e9-8012-a2aa6c0a04be.png)

**Comment by VeraDidenko** [comment]
Hello @oliverdroege , 

 

Thank you for reaching out to us.

 

We are glad to let you know that our team has provided the fix for the problem.

 

We kindly recommend trying the latest update:
kibana-plugin install https://github.com/flexmonster/pivot-kibana/releases/download/v1.21/flexmonster_pivot-v1.21.zip

 

Please let us know if everything works fine for you.

 

We are waiting for your feedback.

 

Best Regards,

Vera

**Comment by AvinashTayal** [comment]
Hi @VeraDidenko ,

I have used this link too.
have run **yarn upgrade**  
and have added all **CORS** configuration in both **Elasticsearch** and **Kibana**
restart them but still **Flexmonster Pivot plugin is missing**

**Comment by mhalaida** [comment]
Hi @AvinashTayal,

Thank you for reaching out.

Please note that the flexmonster_pivot Kibana plugin is enabled by default.

If it is disabled in your case, it might be because of some specific Kibana configurations on your side, so we suggest to check there first.

Also, using the –flexmonster_pivot.enabled=true flag might be a feasible solution as well.

One more thing we recommend is to make sure that the current system user has permission to access the directory where the plugin is located.

Please let us know if this helps.

Best regards,
Mykhailo
