### ISSUE TITLE
plugin compatibility with Elastic 6.X

### ISSUE THREAD

**Issue by piellick** [flexmonster/pivot-kibana#17]
Hi everyone,
does it compatible with Elastic 6.x (6.7 /6.8 ) ?

I'm not able to find compatibility matrix for the plugin.

Thanks.

**Comment by mhalaida** [comment]
Hi @piellick,

Thank you for reaching out.

Please note that the plugin is currently not compatible with versions 6.x of Kibana.

Instead, we usually suggest using the plugin with Kibana version 7.3.2 or modifying the source code of the plugin (in the package.json and/or other files if necessary) so that it becomes compatible with the corresponding Kibana version.

Please let us know if you have any other questions we can help you with.

Best regards,
Mykhailo
