### ISSUE TITLE
Issue in Plugin installation

### ISSUE THREAD

**Issue by SpringTrey** [flexmonster/pivot-kibana#19]
Hi Team,
Trying to install "flexmonster_pivot-v1.14.zip"  in Oracle Linux Server 7.6. 
Kibana version - 7.2
Elastic Version - 7.4.2

Command Used to install from kibana/bin folder - 
 kibana-plugin install file:///home/demoadmin/temp1/flexmonster_pivot-v1.14.zip

Issue :-

Attempting to transfer from file:///home/demoadmin/temp1/flexmonster_pivot-v1.14.zip
Transferring 1984586 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "EACCES: permission denied, open '/u01/app/kibana/kibana-7.2.0-linux-x86_64/plugins/.plugin.installing/package.json'"

Please help.

**Comment by VeraDidenko** [comment]
Hello,

 

Thank you for reaching out to us.


It seems a similar case is discussed in the following thread on our Support Forum: https://www.flexmonster.com/question/pivot-kibana-plugin-installation-eaccess-permission-denied/#answer-24113.

 

Please let us know if this helps.

 

Kind regards,

Vera

**Comment by SpringTrey** [comment]
Hello,

Thanks for your support.

I have installed Kibana in my local windows machine and Elastic is running on another  linux server. I could install flexmonster plugin. But when it is loading index. I could see the error as it trying to connect to localhost elastic search instead of actual ES host provided in kibana.yml.


![flexmonsterissue-1](https://user-images.githubusercontent.com/60910132/74314823-2b01da00-4d9c-11ea-866f-ea8c427fce37.PNG)

**Comment by mhalaida** [comment]
Hi @SpringTrey,

Kindly note that this is a known error in plugin version 1.14, which is the one you seem to be using. It was fixed in version 1.18, however, Kibana version 7.2 is no longer supported in that version of the plugin.

With that in mind, what we would suggest is to update both the plugin to version 1.21 (latest release) and Kibana to 7.3.2 (supported in plugin v 1.21), as this should resolve the issue.

Please let us know if this helps.

Best regards,
Mykhailo

**Comment by samz-github** [comment]
Unzip the file and copy everything inside a kibana/plugins folder to be able to install it.
