### ISSUE TITLE
Plugin no longer works on 7.6.X

### ISSUE THREAD

**Issue by Ander-MZ** [flexmonster/pivot-kibana#20]
According to [this](https://github.com/elastic/kibana/pull/53824), from version 7.6 onwards the Elasticsearch client in JS is no longer exposed as an observable, and now is simply accessed as a static reference.

Therefore, the flexmonster plugin **no longer works** (line 24):

```  1 export default function (kibana) {
  2   return new kibana.Plugin({
  3     require: ['elasticsearch'],
  4     name: 'flexmonster_pivot',
  5     uiExports: {
  6       app: {
  7         title: 'Flexmonster Pivot',
  8         description: 'Flexmonster Pivot Table',
  9         main: 'plugins/flexmonster_pivot/app',
 10         icon: 'plugins/flexmonster_pivot/logo.png'
 11       },
 12     },
 13     config(Joi) {
 14       return Joi.object({
 15         enabled: Joi.boolean().default(true),
 16       }).default();
 17     },
 18     init(server, options) { // eslint-disable-line no-unused-vars
 19       server.route({
 20         path: '/api/flexmonster_pivot/es',
 21         method: 'GET',
 22         handler: (req) => {
 23           return new Promise((resolve, reject) => {
 24             server.newPlatform.setup.core.elasticsearch.dataClient$.subscribe(client => {
 25               const url = new URL(client.config.hosts[0]);
 26               const esConfig = {
 27                 "host": {
 28                   "protocol": url.protocol.replace(/:/g, ''),
 29                   "host": url.hostname,
 30                   "port": url.port,
 31                   "path": url.pathname,
 32                   "headers": {
 33                     "authorization": req.headers.authorization
 34                   }
 35                 }
 36               }
 37               resolve(esConfig);
 38             });
 39           });
 40         }
 41       });
 42     }
 43   });
```
Are there any plans to update the plugin? Or at least any guidance so I can try to fix it myself?

Regards

**Comment by tsshn** [comment]
Hello,

Thank you for your question.

We would like to kindly inform you that the latest version of Kibana compatible with the plugin v.1.21 is version 7.3.2. For now, updating the plugin to support the latest Kibana is not on our road map for the nearest future.

Moreover, it seems that the latest version of the plugin has another issue connected with exceptions while trying to open the index. As a workaround, it may help to refer to react-flexmonster@2.7.24 in the Flexmonster Kibana plugin instead of the latest one. More details about the problem can be found on the following [forum thread](https://www.flexmonster.com/question/uncaught-typeerror-cannot-read-property-bp-of-undefined/).

As for changes in the way the Elasticsearch client is exposed, our team recommends paying attention to the following code snippet:

```
26 const esConfig = {
27     "host": {
28         "protocol": url.protocol.replace(/:/g, ''),
29         "host": url.hostname,
30         "port": url.port,
31         "path": url.pathname,
32         "headers": {
33             "authorization": req.headers.authorization
34         }
35     }
36 }
```

It is possible that the replacement of the current configuration with appropriate data providing a connection to Elasticsearch exposed as a static reference will resolve the problem.

We hope it helps.

Regards,
Illia
